@host = http://localhost:5136

# Valid login (replace <JWT> before running)
POST {{host}}/api/login
Content-Type: application/json
x-auth-token: <JWT>

{
  "username": "user1",
  "password": "Password123"
}

###

### Invalid password
POST {{host}}/api/login
Content-Type: application/json
x-auth-token: <JWT>

{
  "username": "user1",
  "password": "WrongPassword"
}

###

###  Missing token
POST {{host}}/api/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password123"
}

###

### Unknown user
POST {{host}}/api/login
Content-Type: application/json
x-auth-token: <JWT>

{
  "username": "user_not_exist",
  "password": "Password123"
}
